# Generated by Django 5.0.3 on 2024-04-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
