# Generated by Django 5.0.3 on 2024-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_delete_grade'),
        ('users', '0003_remove_subjectteacher_subject_subjectteacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclassroom',
            name='classroom',
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='classroom',
            field=models.ManyToManyField(to='quiz.classroom'),
        ),
    ]
