# Generated by Django 5.0.3 on 2024-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_teacherclassroom_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar1.png', upload_to='profile_pics'),
        ),
    ]
