# Generated by Django 5.0.3 on 2024-04-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='uid',
            new_name='id',
        ),
    ]
