# Generated by Django 5.0.3 on 2024-04-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
