# Generated by Django 5.0.3 on 2024-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_subject_klassenstufe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='class_character',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
    ]
