# Generated by Django 5.0.3 on 2024-04-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.category'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.subject'),
        ),
    ]
