# Generated by Django 5.0.3 on 2024-04-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_is_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
    ]
