# Generated by Django 5.0.3 on 2024-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_delete_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='grade',
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
