# Generated by Django 5.0.3 on 2024-05-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_category_options_remove_category_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='year',
            new_name='class_number',
        ),
    ]
