# Generated by Django 5.0.3 on 2024-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_classroom_teacher_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.subject'),
        ),
    ]
