# Generated by Django 4.2.13 on 2024-05-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.category'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.subject'),
        ),
    ]
