# Generated by Django 4.2.13 on 2024-05-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_score_category_alter_score_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.subject'),
        ),
    ]
