# Generated by Django 5.0.3 on 2024-04-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_publication_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
