# Generated by Django 5.0.3 on 2024-04-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_delete_article_delete_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
